#!/bin/bash

echo "nodejs `node -v`"
echo ""

node lamdaCalculusSumAndProd.js
echo ""
node SumAndProd.js
echo ""
node second.js
echo ""
node explicitFact.js
echo ""
node implicitFact.js
echo ""
node lengthOfSequence.js
